### ISSUE TITLE
Not reloading in Firefox

### ISSUE THREAD

**Issue by ryanhilton** [uicrooks/shopify-foundation-theme#14]
I have turned off all security protections, (including no adblockers, and have whitelisted the domains, and I'm actually using the Firefox developer edition) but Reloader won't reload, and I get the attached errors. I use Firefox almost exclusively, so I would prefer to get it working there.

![ff-trouble](https://user-images.githubusercontent.com/955429/113338705-75734c80-92f7-11eb-83bc-ac5b7cf18b00.jpg)

**Comment by sergejcodes** [comment]
Hi Ryan,

Firefox seems to have some issues with secure and insecure contentions to/from the same domain.

Just tested the following solution in Firefox Developer Edition and it's working for me:

1. type in `about:config` in your address bar
2. go to `security.csp.enable` and disable it by setting it to false
3. restart your browser

If you disable CSP you should probably use a different browser for normal web use.

**Comment by ryanhilton** [comment]
Ah @sergejcodes Thank you! I had tried a few other settings in the about: config, but none worked. I wonder why the csp needs to be turned off in Firefox, but not Chrome for that to work? More strict websockets in Firefox maybe?

I'm new to Shopify theme dev. So Theme Lab (and your projects) have been a tremendous help and time saver for me to see how themes are built, and the modern tool chain you have assembled!

**Comment by sergejcodes** [comment]
Thanks,

it should now be possible to enable a secure connection in `shopify-theme-lab-reloader`. There's no need to adjust any browser settings. Simply update to `shopify-theme-lab-reloader` to >= `2.1.2` and refer to this [guide](https://github.com/uicrooks/shopify-theme-lab-plugins/tree/master/packages/reloader#secure-websocket-connection)

**Comment by ryanhilton** [comment]
Thank you so much @sergejcodes I really owe ya one!
