### ISSUE TITLE
Installing this theme failed

### ISSUE THREAD

**Issue by heyalbert** [uicrooks/shopify-foundation-theme#2]
Schönen Guten Abend Sergej!
I'm loving so far what you're doing here! I'm glad I found this project here — please, keep up this great work: Finally a good new foundation for developing a Shopify theme in 2021! 
I'm sorry, I still don't quite understand how to install your foundation theme on top of Theme Lab. Furthermore, I followed your guidelines here: https://github.com/uicrooks/shopify-theme-lab#getting-started and now I wish to also use the foundation theme as well.

What is the recommended way to install this theme? Because I'm only getting these error messages after copying your files over the Theme Lab files:

```
ERROR in ./src/main.js 7:0-34
Module not found: Error: Can't resolve 'vue-screen' in '/Users/.../src'

ERROR in ./src/main.js 8:0-47
Module not found: Error: Can't resolve 'v-lazy-image' in '/Users/.../src'
```

Thank you for your help!

**Comment by heyalbert** [comment]
Could I be that you want to install it like so?

```
npx themelab create <directory-name> --repo=https://github.com/uicrooks/shopify-foundation-theme
```

This gets me a step further. Unfortunately, the site is still broken as it's not loading all the assets/css.

**Comment by sergejcodes** [comment]
Abend Albert 👋🏻

I think you were already on the right track.

You don't have to install the theme on top `Shopify Theme Lab`. All the files from `Shopify Theme Lab` are already included this theme's repo.

Simply clone this repo like you normally would and run `npm install`. That should fix your issue.

Alternatively, you can run the following command and select the theme from the prompt menu:
```
npx themelab create <directory-name> --preset
```

**Comment by heyalbert** [comment]
Thank you Sergej. This solved it for me!
Can't wait to start building my new Shopify theme with Theme Lab!
