### ISSUE TITLE
https://shopify.github.io/liquid-code-examples/example/product-variant-selector #}

### ISSUE THREAD

**Issue by deniskern** [uicrooks/shopify-foundation-theme#30]
Hier bitte über die Settings zwei Optionen anbieten einmal Seleecet Variations als Image Box und als normales Select.
Alle Varianten müssen einzelnd dargestellt werden

https://github.com/onedot-digital-crew/sp-foundation-theme/blob/6acff05a2a2f7cb186a386879171e03b7415bb66/shopify/templates/product.liquid#L96-L96

**Comment by sergejcodes** [comment]
This request is too specific. Nonetheless, variant options will have distinct select fields in the next release.
