### ISSUE TITLE
Shopify 2.0 theme structure

### ISSUE THREAD

**Issue by madmax124** [uicrooks/shopify-foundation-theme#33]
Any chance of this getting an update according to the new Shopify 2.0 structure?

I love this stack and amazing DX by you guys!

(my bad, this should have been in **discussions**)

**Comment by sergejcodes** [comment]
Shopify recently released some updated Tooling. We have to go through it and figure out if it makes sense to implement and how to do it in the best way possible, so it may take some time. But there are plans to update this project to the latest Shopify standards.

**Comment by sergejcodes** [comment]
The latest [Foundation Theme 4 release](https://github.com/uicrooks/shopify-foundation-theme/releases/tag/v4.0.0) has Shopify CLI and Online Store 2.0 support.
