### ISSUE TITLE
Unable to get past my stores password protection screen (Shopify trial account)

### ISSUE THREAD

**Issue by sidm1983** [uicrooks/shopify-foundation-theme#38]
Hi,

So I just installed the foundation theme using Theme Labs and when I do a `yarn start` as per the instructions, I get a localhost URL as well as a couple of public URLs to customise/preview the foundation theme. The customise/preview public URLs work well, however my localhost URL displays a password screen. When I enter the password that I have set in my Shopify preferences to hide my store, my localhost doesn't accept it and just redirects back to the password page. I believe this is a cookie issue as shopify is returning cookies for the live hostname of the store which then doesn't get set as my browser is currently on the `http://127.0.0.1:<port>` URL. I didn't have this issue before using the Foundation theme. Am I doing something wrong here? Apologies if this is not an issue related to the theme itself. I am extremely new to shopify and all this theme stuff. Would really appreciate if someone can point me in the right direction on how to solve this issue.

Thank you! 🙏🏽

**Comment by sergejcodes** [comment]
This is strange I don't have any issues logging in from the localhost URL. 

Some troubleshooting steps:

1. Have you created the store after June 29, 2021?
2. When creating your store did you select the `development` store option
3. Log out of the store and log in again using the `your-store.myshopify.com/admin` URL
4. Log out of your store via the Shopify CLI `shopify logout` and then log in again `shopify login --store your-store.myshopify.com`
5. Are you sure you are using the right password?

![screen](https://user-images.githubusercontent.com/68379148/126150208-22cdd4ff-ec86-47df-be04-10a4d7751576.png)

**Comment by boomcruiser** [comment]
In the file **shopify/sections/main-password.liquid**  
Changing the  input name from **"customer[password]"** to **"password"** fixed the issue for me. 
Change 
` <input
        type="password"
        id="CustomerPassword"
        name="customer[password]"
        placeholder="{{ 'form.password' | t }}"
        class="w-full rounded-r-none"
        required
      >
`
to 
`<input
        type="password"
        id="CustomerPassword"
        name="password"
        placeholder="{{ 'form.password' | t }}"
        class="w-full rounded-r-none"
        required
      >
`

**Comment by sergejcodes** [comment]
Yes, that's a bug. The solution from @boomcruiser should be correct. I was always getting the default Shopify password template and not the custom one from the theme.

**Comment by sidm1983** [comment]
@boomcruiser @sergejcodes that was it! I actually ended up deleting the theme I previously initialised and re-initialised a new one based on v4.1.1 that you release above and the issue is now gone. I am able to get into my test store locally. Thank you so much for your assistance and the prompt response/fix. Much appreciated! 🙏🏽❤️🙌🏽
