### ISSUE TITLE
[Bug]: Product price doesn't change on variant update

### ISSUE THREAD

**Issue by fowlercraig** [uicrooks/shopify-foundation-theme#46]
### Operating system

macOS Big Sur

### Node.js version

16.9.0

### Shopify CLI version

2.0

### Browsers

Chrome

### Version

4 (Current)

### Modifications

No modifications.

### Details

Hi there, if variants have different pricing (red shirt: $10, blue shirt $20), the product price doesn't change when you swap between the two options. 

### Notice

- [X] I read the notice

**Comment by sergejcodes** [comment]
This issue should be fixed in the latest release
