### ISSUE TITLE
Flashing icons without styles on load

### ISSUE THREAD

**Issue by milosdakic** [uicrooks/shopify-foundation-theme#5]
Awesome work on this template. I loved how simple it was to get started with.

I've been experiencing flashing of content without styles on load. I tried the usual Vue tricks to prevent it but doesn't seem to work. Is there anything you guys can recommend?

**Comment by milosdakic** [comment]
Sorry, found the solution.

**Comment by larsjanssen6** [comment]
@milosdakic how did you fix it?

**Comment by larsjanssen6** [comment]
@sergejcodes thanks!

**Comment by larsjanssen6** [comment]
@sergejcodes hey! I still got this problem with a live-site on shopify https://snuffelbox.nl/. Any idea how I can fix this?

**Comment by sergejcodes** [comment]
Hi 👋, 

I just clicked through your site and all icons seem to be fine, no issues here. I'm on the latest Chrome version. You have to be a bit more specific. One thing you could try is to add an initial fixed width and height to your svgs like this:
```html
<svg width="24" height="24" viewBox="0 0 24 24" >...</svg>
```

**Comment by larsjanssen6** [comment]
Hey! Thanks for the quick reply, much appreciated! I've deployed to production and now it's working indeed. One other issue I have everytime I push to production with: `npm run deploy:live -- --allow-live` it's overwriting my configured shopify images. Any idea why that's happening?

**Comment by sergejcodes** [comment]
Do you mean images you set through the Shopify theme editor? If yes, you should run `npm run settings:live` to download the latest live `settings_data.json` file before deploying. 

By default, the deploy task overrides everything on the remote store, so you have to download the settings file if someone makes separate adjustments on the live store which differ from the dev store.

Depending on your workflow you could incorporate a CI/CD workflow that does exactly that (described in the Shopify Theme Lab readme) and/or [Shopify Settings Control](https://github.com/uicrooks/shopify-settings-control) for backing up the live `settings_data.json` to prevent data loss.

**Comment by larsjanssen6** [comment]
Thanks
