### ISSUE TITLE
Vuex mobile toggle not working

### ISSUE THREAD

**Issue by larsjanssen6** [uicrooks/shopify-foundation-theme#7]
Hi, 

Recently discovered this theme it's really nice! Thanks for your work. Got one question/issue:

When I click in in `sections/layout-mobile-navigation.liquid` on `@click="$store.dispatch('mobile-menu/toggle')"` and I look into my vue devtools no state has been changed. If `vuex` is available on this page is should work right?

Thanks!

**Comment by sergejcodes** [comment]
Hi Lars,

I'm on Chrome version `88` with Vue devtools `5.3.4`. The menu button seems to work fine, the event shows up in the Vuex panel, see the attached image. Can you provide some additional info about your setup?

![screen](https://user-images.githubusercontent.com/68379148/110140190-1c85c680-7dd4-11eb-86fb-71a60194a02a.png)

**Comment by larsjanssen6** [comment]
Thanks, I guess I messed something up :)
